### ISSUE TITLE
Storybook does not run after cloning repository

### ISSUE THREAD

**Issue by TomKrcmar** [chromaui/intro-storybook-svelte-template#1] opened 2021-02-12 16:53 UTC
**Given**:
- A freshly cloned copy of the repository
```
$ npm -v
6.14.8
$ node -v
v14.15.0
```

**When**:
- I run `npm run storybook`

**Expected**:
- Storybook runs and displays the default components

**Actual**:
- Webpack runs and throws the error logged below.
- localhost:6006 shows the storybook UI with infinite loading spinners everywhere and no components

Log (Middle-truncated, denoted with ellipsis "..."):
```
$ npm run storybook

> intro-storybook-svelte-template@1.0.0 storybook D:\projects\taskbox
> start-storybook -p 6006 -s public

info @storybook/svelte v6.1.17
info
info => Loading static files from D:\projects\taskbox\public and serving at /.
info => Using prebuilt manager
info => Loading presets
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook\main.js"
info => Using default Webpack setup
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active
<s> [webpack.Progress] 10% building 0/1 modules 1 active multi D:\Projects\taskbox\node_modules\@storybook\core\dist\server\common\polyfills.js D:\Projects\taskbox\node_modules\@storybook\core\dist\server\preview\globals.js D:\projects\taskbox\.storybook\storybook-init-framework-entry.js D:\projects\taskbox\node_modules\@storybook\addon-docs\dist\frameworks\common\config.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-docs\dist\frameworks\svelte\config.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-links\dist\preset\addDecorator.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-actions\dist\preset\addDecorator.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-actions\dist\preset\addArgs.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-backgrounds\dist\preset\addDecorator.js-generated-other-entry.js D:\projects\taskbox\node_modules\@storybook\addon-backgrounds\dist\preset\addParameter.js-generated-other-entry.js D:\projects\taskbox\.storybook\preview.js-generated-config-entry.js D:\projects\taskbox\.storybook\generated-stories-entry.js D:\Projects\taskbox\node_modules\webpack-hot-middleware\client.js?reload=true&quiet=false&noInfo=undefined
<s> [webpack.Progress] 10% building 1/1 modules 0 active
<s> [webpack.Progress] 10% building 1/2 modules 1 active D:\projects\taskbox\.storybook\storybook-init-framework-entry.js
<s> [webpack.Progress] 10% building 1/3 modules 2 active D:\projects\taskbox\.storybook\preview.js-generated-config-entry.js
<s> [webpack.Progress] 10% building 2/3 modules 1 active D:\projects\taskbox\.storybook\preview.js-generated-config-entry.js
<s> [webpack.Progress] 10% building 3/3 modules 0 active

...

<s> [webpack.Progress] 87% after chunk id optimization
<s> [webpack.Progress] 87% record modules
<s> [webpack.Progress] 87% record modules RecordIdsPlugin
<s> [webpack.Progress] 87% record chunks
<s> [webpack.Progress] 87% record chunks RecordIdsPlugin
<s> [webpack.Progress] 88% hashing
<s> [webpack.Progress] 88% after hashing
<s> [webpack.Progress] 88% after hashing HotModuleReplacementPlugin
<s> [webpack.Progress] 89% record hash
<s> [webpack.Progress] 89% module assets processing
<s> [webpack.Progress] 90% chunk assets processing
<s> [webpack.Progress] 90% additional chunk assets processing
<s> [webpack.Progress] 90% additional chunk assets processing HotModuleReplacementPlugin
<s> [webpack.Progress] 91% recording
<s> [webpack.Progress] 91% recording HotModuleReplacementPlugin
<s> [webpack.Progress] 92% additional asset processing
<s> [webpack.Progress] 92% additional asset processing PersistentChildCompilerSingletonPlugin
<s> [webpack.Progress] 92% chunk asset optimization
<s> [webpack.Progress] 93% after chunk asset optimization
<s> [webpack.Progress] 93% after chunk asset optimization SourceMapDevToolPlugin
(node:8664) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at fromStringWithSourceMap (D:\Projects\taskbox\node_modules\source-list-map\lib\fromStringWithSourceMap.js:15:32)
    at SourceMapSource.listMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\SourceMapSource.js:45:10)
    at ReplaceSource.listMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\ReplaceSource.js:140:26)
    at CachedSource.listMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\CachedSource.js:22:24)
    at ConcatSource.listMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\ConcatSource.js:72:18)
    at ConcatSource.proto.sourceAndMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\SourceAndMapMixin.js:24:16)
    at CachedSource.sourceAndMap (D:\Projects\taskbox\node_modules\webpack-sources\lib\CachedSource.js:58:31)
    at getTaskForFile (D:\Projects\taskbox\node_modules\webpack\lib\SourceMapDevToolPlugin.js:65:30)
    at D:\Projects\taskbox\node_modules\webpack\lib\SourceMapDevToolPlugin.js:215:20
    at Array.forEach (<anonymous>)
    at D:\Projects\taskbox\node_modules\webpack\lib\SourceMapDevToolPlugin.js:186:12
    at SyncHook.eval [as call] (eval at create (D:\Projects\taskbox\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:14:1)
    at SyncHook.lazyCompileHook (D:\Projects\taskbox\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Projects\taskbox\node_modules\webpack\lib\Compilation.js:1413:42
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Projects\taskbox\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Projects\taskbox\node_modules\tapable\lib\Hook.js:154:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dbrezack** [comment] 2021-02-28 23:25
@TomKrcmar Have you tried setting it to W for wumbo ?

**Comment by jonniebigodes** [comment] 2021-03-26 20:52
Hi @TomKrcmar first and foremost sorry that you ran into an issue with this template. Secondly sorry for the radio silence but I've been taking care of some other tasks!

I took some time to look into this issue and I wasn't able to reproduce the issue.

I did a couple of tests with this:
- Ran it on a macOS and no issues there.
- Partitioned my windows 10 box hd and created a `D:\` drive with the same folder structure you've mentioned and still no luck. 

In either OS test this was the result I got.

![svelte-template-running-npm](https://user-images.githubusercontent.com/22988955/112690542-de7c3f80-8e73-11eb-9dc8-1b4c53bdad6a.png)


If you could provide any additional context to your case I would gladly adjust accordingly and test it.

Let me know and we'll proceed from there.

Stay safe

**Comment by jonniebigodes** [comment] 2021-04-23 19:52
@TomKrcmar going to close this issue if you don't mind. I've been testing a bit more with the updates for Storybook 6.2 and wasn't able to reproduce it. The same testing methodology was applied to my comment above and it's working.

Let me know of any further developments and I'll gladly re-open this.

Stay safe

**Closed as completed by jonniebigodes** 2021-04-23 19:52 UTC

**Comment by TomKrcmar** [comment] 2021-05-26 16:19
@jonniebigodes Thanks for the attentive assistance - It took a long time to realize, but I eventually found the issue was with my shell starting in a directory with different path capitalization than the true folder names, which Windows and some parts of webpack disagreed on how to handle. My shell always came up that way because I had a shortcut to that cwd on my desktop 🤦‍♂️

**Comment by jonniebigodes** [comment] 2021-05-27 14:50
@TomKrcmar no problem. Glad that you managed to sort it out and get to the root cause of the issue. 

Let me know of any further issues you encounter.

Stay safe
